// Taxpayer 360°: the taxpayer's e-way bills against its returns (see src/engine/ewb.js).
import React from 'react';
import { Card, Kpi, DataTable } from './ui.jsx';
import Icon from './Icon.jsx';
import { useEwbSync, SyncProgress } from './EwbSync.jsx';
import { inr, int, pct } from '../lib/format.js';

const when = (at) => String(at || '').replace('T', ' ');

export default function EwbTab({ a, reload, toast }) {
  const sync = useEwbSync({ reload, toast });
  const e = a.ewb;
  const syncBar = (
    <div className="card" style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap', padding: '10px 14px', marginBottom: 12 }}>
      <button className="btn small" onClick={() => sync.start(a.gstin)} disabled={sync.running} title="Fetch this GSTIN's e-way bills again and re-run the checks">
        <Icon name="truck" size={15} />{sync.running ? 'Syncing…' : 'Sync e-way bills'}
      </button>
      <SyncProgress job={sync.job} lastSynced={e?.fetchedAt} />
      {e && !sync.running && <span className="muted" style={{ fontSize: 13 }}>{e.source === 'upload' ? '· from an uploaded export ' : ''}· matched to GSTR-1 and GSTR-2B by supplier GSTIN and document number</span>}
    </div>
  );
  if (!e) return <>{syncBar}<Card><div className="empty">No e-way bill data for this taxpayer-year yet. Use <b>Sync e-way bills</b> above.</div></Card></>;
  const o = e.outward, i = e.inward, s = e.shipTo;
  return (
    <>
      {syncBar}
      <div className="grid g-4">
        <Kpi label="Bills generated" value={int(o.bills)} sub={`${inr(o.value)} moved · ${int(o.cancelled)} cancelled`} />
        <Kpi label="Sales invoices covered" value={pct(o.needing ? o.covered / o.needing : null)} sub={`${int(o.covered)} of ${int(o.needing)} above the limit`} fill={o.needing ? o.covered / o.needing : 0} />
        <Kpi label="Purchase invoices covered" value={pct(i.needing ? i.covered / i.needing : null)} sub={`${int(i.covered)} of ${int(i.needing)} goods invoices above the limit`} fill={i.needing ? i.covered / i.needing : 0} />
        <Kpi label="Bills received" value={int(i.bills)} sub="generated by suppliers for goods coming in" />
      </div>

      <Card title="Goods moved with no invoice in GSTR-1 (G-05)" sub={o.unmatched.count ? `${int(o.unmatched.count)} bills · ${inr(o.unmatched.value)} · tax ${inr(o.unmatched.tax)}: the goods left, the sale was not reported` : 'Every bill the taxpayer generated matches an invoice in GSTR-1.'} style={{ marginTop: 12 }}>
        {o.unmatched.count > 0 && <DataTable columns={['E-way bill', 'Generated', 'Document', 'To', 'Value', 'Vehicle']} rows={o.unmatched.rows.map((b) => [b.no, when(b.at), b.docNo, b.toName || b.to, b.total, b.vehicle || '-'])} total={o.unmatched.count} />}
      </Card>

      <Card title="ITC on goods with no e-way bill (B-03)" sub={i.unsupported.count ? `${int(i.unsupported.count)} purchase invoices · ITC ${inr(i.unsupported.itc)} with no record that the goods moved. Ask for proof of receipt: GRN, lorry receipt, stock entry.` : 'Every goods purchase above the limit has an e-way bill behind it.'} style={{ marginTop: 12 }}>
        {i.unsupported.count > 0 && <DataTable columns={['Supplier', 'GSTIN', 'Invoice', 'Date', 'Value', 'ITC']} rows={i.unsupported.rows.map((x) => [x.party, x.from, x.no, x.date, x.value, x.itc])} total={i.unsupported.count} />}
      </Card>

      <Card title="Bill-to-ship-to movements (D-05)" sub={s.moves ? `${int(s.moves)} movements delivered to another state than the bill-to party's${s.wrongHead.count ? `; ${s.wrongHead.count} charged the wrong tax head (tax ${inr(s.wrongHead.tax)})` : ', all under the right tax head'}` : 'None in the e-way bill data.'} style={{ marginTop: 12 }}>
        {s.wrongHead.count > 0 && <DataTable columns={['E-way bill', 'Invoice', 'Bill-to state', 'Ship-to state', 'IGST', 'CGST', 'SGST']} rows={s.wrongHead.rows.map((x) => [x.no, x.docNo, x.billTo, x.shipTo, x.igst, x.cgst, x.sgst])} total={s.wrongHead.count} />}
      </Card>

      <Card title="Same vehicle in two places at once" sub={e.vehicles.clashes ? `${e.vehicles.clashes} impossible journeys: at least one bill of each pair records a movement that did not happen` : 'No vehicle appears on two distant journeys within a few hours.'} style={{ marginTop: 12 }}>
        {e.vehicles.clashes > 0 && <DataTable columns={['Vehicle', 'First bill', 'Started', 'From (PIN)', 'Second bill', 'Started', 'From (PIN)', 'Apart (km)']} rows={e.vehicles.rows.map((v) => [v.vehicle, v.first, when(v.firstAt), v.firstFrom, v.second, when(v.secondAt), v.secondFrom, v.km])} />}
      </Card>

      {o.missing.count > 0 && (
        <Card title="Sales invoices above the limit with no e-way bill" sub={`${int(o.missing.count)} invoices · ${inr(o.missing.value)}. Not a finding on its own (goods may have moved by the buyer's own bill, or not at all for a service); worth a question.`} style={{ marginTop: 12 }}>
          <DataTable columns={['Invoice', 'Date', 'Buyer', 'GSTIN', 'Value']} rows={o.missing.rows.map((x) => [x.no, x.date, x.party, x.to, x.value])} total={o.missing.count} />
        </Card>
      )}
    </>
  );
}
