import React, { useEffect, useMemo, useState } from 'react';
import { BRAND, BRAND_SOFT } from '../lib/colors.js';
import Icon from './Icon.jsx';
import { Seg } from './ui.jsx';
import { taxpayerInsights, portfolioInsights } from '../engine/insights.js';
import { taxpayerFacts, portfolioFacts, aiSummarise, aiStatus, insightCacheKey, AI_MODELS } from '../lib/ai.js';
import { CONCLUSIVE } from '../engine/verify.js';

const SEV = {
  critical: { color: '#b02222', bg: '#f8e9e9', glyph: '!', label: 'Critical' },
  warning: { color: '#9c630d', bg: '#faf4dc', glyph: '▲', label: 'Watch' },
  info: { color: BRAND, bg: BRAND_SOFT, glyph: 'i', label: 'Context' },
  good: { color: '#0c6a4a', bg: '#e6f2ec', glyph: '✓', label: 'Clean' },
};

// Key insights, from the deterministic engine or from AI: the officer chooses.
export default function Insights({ scope, a, data, ai, setAi, cache, setCache, go, compact = false, hidden = false, setHidden }) {
  const catalog = data.catalog;
  const [status, setStatus] = useState(undefined); // undefined = checking, null = no proxy
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [expanded, setExpanded] = useState(false);
  useEffect(() => { aiStatus().then(setStatus); }, []);

  const det = useMemo(() => (scope === 'portfolio' ? portfolioInsights(data) : taxpayerInsights(a, catalog)), [scope, a, data, catalog]);
  const pack = useMemo(() => (scope === 'portfolio' ? portfolioFacts(data, ai.mask) : taxpayerFacts(a, catalog, ai.mask)), [scope, a, data, catalog, ai.mask]);
  const cacheKey = insightCacheKey(scope, scope === 'portfolio' ? 'all' : a.id, pack.facts, ai);
  const aiResult = cache[cacheKey];
  const connected = status && (status.envKey || ai.key);
  const mode = ai.mode;
  const result = mode === 'ai' ? aiResult : det;

  const run = async () => {
    setBusy(true); setError(null);
    try {
      const r = await aiSummarise({ scope, facts: pack.facts, refs: pack.refs, masker: pack.masker, settings: ai });
      setCache((c) => {
        const next = { ...c, [cacheKey]: r };
        const keys = Object.keys(next); // keep the cache small
        return keys.length > 40 ? Object.fromEntries(keys.slice(-40).map((k) => [k, next[k]])) : next;
      });
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  const items = result ? (expanded || !compact ? result.items : result.items.slice(0, 5)) : [];
  const live = !!connected;
  if (hidden) return null;
  const modelLabel = AI_MODELS.find((m) => m.id === (aiResult?.meta?.model || ai.model))?.label || aiResult?.meta?.model || ai.model;

  // Cached AI briefings may predate the verification-first prompt: filter their steps at render time too.
  const rawActions = result?.actions || [];
  const actions = mode === 'ai' ? rawActions.filter((x) => !CONCLUSIVE.test(x)) : rawActions;
  const droppedActions = (aiResult?.droppedActions || 0) + (rawActions.length - actions.length);
  return (
    <section className="card insights">
      <div className="card-head">
        <div>
          <div className="eyebrow">{scope === 'portfolio' ? 'Portfolio briefing' : 'Taxpayer briefing'}</div>
          <h3 style={{ marginTop: 6 }}>Key insights</h3>
        </div>
        <div className="actions">
          <span className={`live ${live ? '' : 'off'}`} title={live ? 'AI connection is live' : 'AI is not connected'}><i />{live ? 'AI live' : 'AI off'}</span>
          <Seg value={mode} onChange={(v) => setAi((s) => ({ ...s, mode: v }))} options={[{ value: 'deterministic', label: 'Deterministic' }, { value: 'ai', label: 'AI' }]} />
          {setHidden && <button className="icon-x" onClick={() => setHidden(true)} aria-label="Close key insights" title="Close">×</button>}
        </div>
      </div>

      <div className="ins-mode">
        {mode === 'deterministic' ? (
          <span><Icon name="rules" size={14} /> Rule-based: generated from the checks and signals above: same input, same output.</span>
        ) : (
          <span>
            <Icon name="wave" size={14} /> {aiResult ? <>Generated by <b>{modelLabel}</b> · {new Date(aiResult.meta.at).toLocaleString('en-IN')} · {Math.round((aiResult.meta.ms || 0) / 100) / 10}s{aiResult.meta.usage?.total_tokens ? ` · ${aiResult.meta.usage.total_tokens.toLocaleString('en-IN')} tokens` : ''} · {aiResult.meta.masked ? 'identities masked' : 'identities sent'}</> : <>Uses {modelLabel}. Sends a summary of findings{ai.mask ? ' with names and GSTINs masked' : ''}: never raw invoices.</>}
          </span>
        )}
        {mode === 'ai' && (
          <span style={{ marginLeft: 'auto', display: 'flex', gap: 6 }}>
            {connected && <button className="btn small primary" onClick={run} disabled={busy}>{busy ? 'Summarising…' : aiResult ? 'Regenerate' : 'Generate AI summary'}</button>}
            <button className="btn small" onClick={() => go('ai')}>AI settings</button>
          </span>
        )}
      </div>

      {mode === 'ai' && status === null && <div className="note" style={{ marginTop: 12 }}>AI summaries need the local dev server (<code>npm run dev</code>). This build has no AI proxy: switch to Deterministic.</div>}
      {mode === 'ai' && status && !connected && (
        <div className="callout info" style={{ marginTop: 12, padding: '14px 16px' }}>
          <Icon name="lock" size={17} style={{ flexShrink: 0, marginTop: 2 }} />
          <div>AI is not connected. Add your API key in <a href="#/ai" onClick={(e) => { e.preventDefault(); go('ai'); }}>Configure → AI assistant</a>, or set <code>AI_API_KEY</code> in <code>.env.local</code> and restart <code>npm run dev</code>.</div>
        </div>
      )}
      {error && <div className="callout" style={{ marginTop: 12, padding: '14px 16px', background: 'var(--live-bg)', color: 'var(--critical)' }}><Icon name="alert" size={17} style={{ flexShrink: 0, marginTop: 2 }} /><div>{error}</div></div>}
      {mode === 'ai' && connected && !aiResult && !busy && !error && (
        <div className="empty" style={{ padding: 22 }}>No AI summary yet for this {scope === 'portfolio' ? 'portfolio' : 'taxpayer'} with these settings. Choose <b>Generate AI summary</b>.</div>
      )}
      {busy && <div className="empty" style={{ padding: 22 }}>Asking the AI… usually 10 to 30 seconds.</div>}

      {result && !busy && (
        <>
          <p className="ins-headline">{result.headline}</p>
          <div className={`ins-list ${compact ? '' : 'two'}`}>
            {items.map((it, i) => {
              const s = SEV[it.severity] || SEV.info;
              return (
                <div className="ins-item" key={i}>
                  <span className="ins-ic" style={{ background: s.bg, color: s.color }} title={s.label}>{s.glyph}</span>
                  <div style={{ minWidth: 0 }}>
                    <div className="ins-t">{it.title}</div>
                    <div className="ins-d">{it.detail}</div>
                    {it.unverified?.length > 0 && <div className="ins-warn" title="These amounts do not match any value in the source data">⚠ Figure not found in source data: {it.unverified.join(', ')}: check before relying on it</div>}
                    {it.refs?.length > 0 && <div className="ins-refs">{it.refs.map((r) => <span key={r} className="chip" title={r.startsWith('FR:') ? 'Risk indicator: lead for enquiry, not proof' : catalog.find((c) => c.id === r)?.check}>{r.replace('FR:', 'indicator: ')}</span>)}</div>}
                  </div>
                </div>
              );
            })}
          </div>
          {compact && result.items.length > 5 && <button className="btn ghost small" onClick={() => setExpanded((v) => !v)}>{expanded ? 'Show fewer' : `Show all ${result.items.length}`}</button>}
          {actions.length > 0 && (
            <div className="ins-actions">
              <div className="eyebrow" style={{ marginBottom: 8 }}>Verification steps</div>
              <ol>{actions.map((x, i) => <li key={i}>{x}</li>)}</ol>
            </div>
          )}
          <div className="ins-prelim">Preliminary system findings: not a determination of liability, fraud or intent. Verify before any action.</div>
          {mode === 'ai' && (
            <div className="card-foot">
              AI-generated from the facts shown elsewhere on this page; verify against the findings before acting.
              {aiResult?.droppedRefs > 0 && ` ${aiResult.droppedRefs} unsupported rule reference(s) were removed.`}
              {droppedActions > 0 && ` ${droppedActions} step(s) instructing payment, reversal or a notice were removed.`}
              {aiResult?.unverifiedFigures?.length > 0 ? ` ${aiResult.unverifiedFigures.length} figure(s) could not be matched to the source data and are marked ⚠.` : aiResult ? ' All ₹ figures match the source data.' : ''}
            </div>
          )}
        </>
      )}
    </section>
  );
}
