// Simulated e-way bill system. Stands in for the NIC e-way bill API until GSP credentials are available: for a
// taxpayer-year it produces what the API would return (bills generated by the taxpayer, and bills generated by its
// suppliers for goods coming to it), derived from the invoices in its returns under rule 138, plus the planted
// problems of the high-risk taxpayers. Deterministic: every decision is a hash of the document it concerns, so a
// seller's copy and a buyer's copy of the same bill (or of the same missing bill) always agree.
//
//   data/ewb/<GSTIN>_<FY start>.json  { meta, columns, outward: [row...], inward: [row...] }
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { CITIES, needsEwb, distanceKm, mainHsnOf, inwardHsn } from '../../src/engine/ewb.js';
import { stateCodeOf } from '../../src/engine/parse.js';
import { gstin as makeGstin } from './lib.mjs';

export const SIM_VERSION = 'ewb-sim-v2';
const KEYS = ['no', 'at', 'supply', 'sub', 'doc', 'docNo', 'docDate', 'from', 'fromName', 'fromState', 'fromPin', 'to', 'toName', 'toState', 'toPin', 'shipTo', 'hsn', 'taxable', 'igst', 'cgst', 'sgst', 'cess',
  'total', 'mode', 'vehicle', 'transporter', 'km', 'validUpto', 'status'];

// ------------------------------------------------------------------ deterministic randomness
const hash = (s) => crypto.createHash('sha256').update(s).digest();
const u = (s) => hash(s).readUInt32BE(0) / 2 ** 32;
const pickBy = (arr, s) => arr[Math.floor(u(s) * arr.length)];
const r2 = (v) => Math.round(v * 100) / 100;
const addDays = (iso, n) => { const d = new Date(`${iso}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + n); return d.toISOString().slice(0, 10); };
const hhmm = (s, from = 8, span = 11) => { const x = u(s); const h = from + Math.floor(x * span); const m = Math.floor((x * span * 60) % 60); return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`; };

// ------------------------------------------------------------------ places, vehicles, numbers
const citiesOf = (state) => { const c = CITIES.filter((x) => x[0] === String(state).padStart(2, '0')); return c.length ? c : CITIES.filter((x) => x[0] === '27'); };
const placeOf = (gstin, state) => pickBy(citiesOf(state), `city|${gstin}`);
const RTO = { 27: 'MH', 24: 'GJ', 29: 'KA', 33: 'TN', 36: 'TS', 7: 'DL', 8: 'RJ', 9: 'UP', 19: 'WB', 22: 'CG', 23: 'MP', 30: 'GA', 32: 'KL' };
const L = 'ABCDEFGHJKLMNPRSTUVWXYZ';
const vehicleOf = (gstin, state, k) => { // a fleet of 60 per consignor, plates from its state
  const s = `veh|${gstin}|${k % 60}`;
  return `${RTO[Number(state)] || 'MH'}${String(1 + Math.floor(u(s + 'd') * 48)).padStart(2, '0')}${L[Math.floor(u(s + 'a') * L.length)]}${L[Math.floor(u(s + 'b') * L.length)]}${String(1000 + Math.floor(u(s + 'n') * 8999))}`;
};
const ewbNo = (from, docNo, docDate, k = 0) => `${1 + Math.floor(u(`ewbp|${from}`) * 3)}${String(Math.floor(u(`ewb|${from}|${docNo}|${docDate}|${k}`) * 1e11)).padStart(11, '0')}`;
const transporterOf = (from) => makeGstin(from.slice(0, 2), `ZZ${L[Math.floor(u(`tr|${from}`) * 20)]}T${L[Math.floor(u(`tr2|${from}`) * 20)]}${String(1000 + Math.floor(u(`tr3|${from}`) * 8999))}${L[Math.floor(u(`tr4|${from}`) * 20)]}`);

// ------------------------------------------------------------------ planted problems
// noMovement: [supplier, buyer, share]: invoices between them with no e-way bill at all (goods never moved). Applied
// on both sides. suppressed: share of extra bills a consignor generates with no invoice in its GSTR-1 (sales kept off
// the returns). vehicleClash: planted impossible journeys. cancel: share of bills cancelled and generated again.
const W = (pan) => makeGstin(27, pan); // the PUNE-WARD-01 ward (scripts/synth/ward.mjs)
const BASE_PLAN = {
  noMovement: [[W('ZZSPS9909T'), W('ZZSFS8808S'), 0.6], [W('ZZSFS8808S'), W('ZZTCT7707R'), 0.85], [W('ZZVFV1616A'), W('ZZTCT7707R'), 0.85], [W('ZZSFS8808S'), W('ZZOFO1010U'), 0.5], [W('ZZOFO1010U'), W('ZZSPS9909T'), 0.5]],
  suppressed: { [W('ZZSFS8808S')]: 0.03, '27ZZUCD3562J1ZZ': 0.015 },
  vehicleClash: { [W('ZZSFS8808S')]: 2 },
  cancel: {},
  shipTo: {},
};
let planCache = null;
export function loadPlan(root) {
  if (planCache) return planCache;
  const plan = JSON.parse(JSON.stringify(BASE_PLAN));
  for (const unit of ['corporates', 'ltu-pune']) { // the large-taxpayer units (corporates.mjs, ltu-pune.mjs)
    const f = path.join(root, 'test-data', unit, 'ewb-plan.json');
    if (!fs.existsSync(f)) continue;
    const p = JSON.parse(fs.readFileSync(f, 'utf8'));
    plan.noMovement.push(...(p.noMovement || []));
    Object.assign(plan.suppressed, p.suppressed || {}); Object.assign(plan.vehicleClash, p.vehicleClash || {}); Object.assign(plan.cancel, p.cancel || {}); Object.assign(plan.shipTo, p.shipTo || {});
  }
  plan.nm = new Map(plan.noMovement.map(([s, b, share]) => [`${s}|${b}`, share]));
  plan.hash = crypto.createHash('sha256').update(JSON.stringify([plan.noMovement, plan.suppressed, plan.vehicleClash, plan.cancel, plan.shipTo])).digest('hex').slice(0, 12);
  planCache = plan;
  return plan;
}
const neverMoved = (plan, supplier, buyer, docNo) => { const share = plan.nm.get(`${supplier}|${buyer}`); return share != null && u(`nm|${supplier}|${docNo}`) < share; };

// ------------------------------------------------------------------ one bill
function bill({ from, fromName, fromState, to, toName, toState, shipTo, docNo, docDate, hsn, taxable, igst, cgst, sgst, total, sub = 'Supply', doc = 'Tax Invoice', supply, k = 0, status = 'Active', at }) {
  const src = placeOf(from, fromState);
  const dst = placeOf(to, shipTo || toState);
  const km = Math.max(8, distanceKm(src[2], dst[2]) ?? 350);
  const bulk = /^(2523|2701|7208|7214|7204)/.test(hsn);
  const mode = bulk && km > 700 && u(`rail|${from}|${docNo}`) < 0.35 ? 'Rail' : 'Road';
  const when = at || `${docDate}T${hhmm(`t|${from}|${docNo}|${k}`)}`;
  return {
    no: ewbNo(from, docNo, docDate, k), at: when, supply, sub, doc, docNo, docDate, from, fromName, fromState, fromPin: src[2], to, toName, toState, toPin: dst[2], shipTo: shipTo || '', hsn,
    taxable: r2(taxable), igst: r2(igst), cgst: r2(cgst), sgst: r2(sgst), cess: 0, total: r2(total), mode,
    vehicle: mode === 'Road' ? vehicleOf(from, fromState, Math.floor(u(`v|${from}|${docNo}`) * 60)) : '', transporter: transporterOf(from), km,
    validUpto: `${addDays(when.slice(0, 10), Math.max(1, Math.ceil(km / 200)))}T23:59`, status,
  };
}

/**
 * The e-way bills for one parsed taxpayer-year, as the e-way bill system would return them.
 * @returns {{ outward: object[], inward: object[] }}
 */
export function simulate(tp, plan) {
  const own = String(tp.stateCode);
  const hsnOut = mainHsnOf(tp);
  const out = [];
  const cancelShare = plan.cancel[tp.gstin] ?? 0.01;
  const withCancel = (b, x, mk) => {
    if (u(`c|${b.from}|${b.docNo}`) < cancelShare) { // cancelled within the day, generated again
      const c = mk(1); c.status = 'Cancelled'; c.at = `${b.docDate}T${hhmm(`tc|${b.from}|${b.docNo}`, 7, 2)}`;
      return [c, b];
    }
    return [b];
  };
  // bills the taxpayer generated for its own supplies
  for (const x of [...tp.b2b, ...(tp.b2cl || [])]) {
    const toState = stateCodeOf(x.pos) || own;
    if (!needsEwb({ supplierName: tp.name, value: x.value, fromState: own, toState, hsn: hsnOut(x.m) })) continue;
    if (neverMoved(plan, tp.gstin, x.gstin, x.no)) continue;
    const shipTo = plan.shipTo[`${tp.gstin}|${x.no}`];
    const mk = (k) => bill({ from: tp.gstin, fromName: tp.name, fromState: own, to: x.gstin || 'URP', toName: x.party || '', toState, shipTo, docNo: x.no, docDate: x.date, hsn: hsnOut(x.m), taxable: x.taxable, igst: x.igst, cgst: x.cgst, sgst: x.sgst, total: x.value, supply: 'Outward', k });
    out.push(...withCancel(mk(0), x, mk));
  }
  // sales moved without an invoice in GSTR-1: to unregistered buyers, numbered in the taxpayer's own series
  const share = plan.suppressed[tp.gstin] || 0;
  if (share && tp.b2b.length) {
    const n = Math.max(3, Math.round(out.length * share));
    const vals = tp.b2b.map((x) => x.taxable).sort((a, b) => a - b);
    const typical = vals[Math.floor(vals.length * 0.6)] || 100000;
    for (let i = 0; i < n; i++) {
      const seedX = tp.b2b[Math.floor(u(`s|${tp.gstin}|${tp.fyStart}|${i}`) * tp.b2b.length)];
      const docNo = String(seedX.no).replace(/(\d+)$/, (d) => String(Number(d) + 70000 + i).padStart(d.length, '0'));
      const taxable = typical * (0.6 + u(`sv|${tp.gstin}|${i}`) * 0.9);
      const intra = u(`si|${tp.gstin}|${i}`) < 0.7;
      const toState = intra ? own : pickBy(['24', '23', '29', '22'], `st|${tp.gstin}|${i}`);
      const rate = 18, tax = (taxable * rate) / 100;
      out.push(bill({ from: tp.gstin, fromName: tp.name, fromState: own, to: 'URP', toName: 'UNREGISTERED PERSON', toState, docNo, docDate: seedX.date, hsn: hsnOut(seedX.m), taxable,
        igst: intra ? 0 : tax, cgst: intra ? tax / 2 : 0, sgst: intra ? tax / 2 : 0, total: taxable + tax, supply: 'Outward' }));
    }
  }
  // bills the suppliers generated for goods coming to the taxpayer
  const inw = [];
  for (const x of tp.g2b) {
    if (x.rc) continue;
    const fromState = String(x.gstin).slice(0, 2);
    const hsn = inwardHsn(x.party, hsnOut(null));
    if (!needsEwb({ supplierName: x.party, value: x.value, fromState, toState: own, hsn })) continue;
    if (neverMoved(plan, x.gstin, tp.gstin, x.no)) continue;
    const shipTo = plan.shipTo[`${x.gstin}|${x.no}`];
    const mk = (k) => bill({ from: x.gstin, fromName: x.party, fromState, to: tp.gstin, toName: tp.name, toState: own, shipTo, docNo: x.no, docDate: x.date, hsn, taxable: x.taxable, igst: x.igst, cgst: x.cgst, sgst: x.sgst, total: x.value, supply: 'Inward', k });
    inw.push(mk(0));
  }
  // impossible journeys: one of the taxpayer's vehicles also shown carrying a supplier's consignment far away, hours apart
  const clashes = plan.vehicleClash[tp.gstin] || 0;
  const far = inw.filter((b) => (distanceKm(b.fromPin, out[0]?.fromPin) ?? 0) > 300);
  for (let i = 0; i < clashes && far.length && out.length; i++) {
    const b1 = out[Math.floor(u(`vc1|${tp.gstin}|${tp.fyStart}|${i}`) * out.length)];
    const b2 = far[Math.floor(u(`vc2|${tp.gstin}|${tp.fyStart}|${i}`) * far.length)];
    if (!b1.vehicle || b1.no === b2.no) continue;
    b2.vehicle = b1.vehicle; b2.mode = 'Road';
    const t = new Date(`${b1.at}:00Z`); t.setUTCHours(t.getUTCHours() + 2);
    b2.at = t.toISOString().slice(0, 16);
  }
  return { outward: out, inward: inw };
}

// ------------------------------------------------------------------ the store
export const ewbFile = (dataDir, gstin, fyStart) => path.join(dataDir, 'ewb', `${gstin}_${fyStart}.json`);
const toRows = (bills) => bills.map((b) => KEYS.map((k) => b[k] ?? null));
const fromRows = (cols, rows) => rows.map((r) => Object.fromEntries(cols.map((c, i) => [c, r[i]])));
export function writeEwb(file, { meta, outward, inward }) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify({ meta, columns: KEYS, outward: toRows(outward), inward: toRows(inward) }));
}
export function readEwb(file) {
  const j = JSON.parse(fs.readFileSync(file, 'utf8'));
  return { ...j.meta, outward: fromRows(j.columns, j.outward), inward: fromRows(j.columns, j.inward) };
}

/**
 * E-way bills for a parsed taxpayer-year: the stored copy (fetched or uploaded), or, when none is stored and
 * simulation is on, a fresh simulated fetch that is stored for next time. Returns null when there is none.
 */
export function ewbFor({ dataDir, root, tp, simulate: sim = process.env.EWB_SIMULATE !== '0' }) {
  const file = ewbFile(dataDir, tp.gstin, tp.fyStart);
  const plan = sim ? loadPlan(root) : null;
  if (fs.existsSync(file)) {
    const e = readEwb(file);
    if (e.source !== 'simulated' || !sim || (e.version === SIM_VERSION && e.plan === plan.hash)) return e;
  }
  if (!sim) return null;
  const { outward, inward } = simulate(tp, plan);
  const meta = { gstin: tp.gstin, fy: tp.fyStart, source: 'simulated', version: SIM_VERSION, plan: plan.hash, fetchedAt: new Date().toISOString() };
  writeEwb(file, { meta, outward, inward });
  return { ...meta, outward, inward };
}
