// E-way bills: syncing the e-way bill data (scripts/ewb-store.js; the source is the simulated e-way bill system until
// NIC/GSP credentials are available, see the README), and what the bills show against the returns across every
// loaded taxpayer: goods moved with no invoice (G-05), credit taken on goods with no movement behind it (B-03),
// bill-to-ship-to movements under the wrong tax head (D-05), and vehicles recorded in two places at once.
import React, { useEffect, useMemo, useState } from 'react';
import { Card, Kpi, PageHead, Band } from '../components/ui.jsx';
import Icon from '../components/Icon.jsx';
import { useEwbSync, SyncProgress } from '../components/EwbSync.jsx';
import { api } from '../lib/api.js';
import { inr, int, pct } from '../lib/format.js';

export default function EwayBills({ data, openTaxpayer, toast, reload }) {
  const [status, setStatus] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [upGstin, setUpGstin] = useState('');
  const loadStatus = () => fetch(api('/__ewb/status'), { cache: 'no-store' }).then((r) => (r.ok ? r.json() : null)).then(setStatus).catch(() => setStatus(null));
  useEffect(() => { loadStatus(); }, [data]);
  const sync = useEwbSync({ reload, toast });

  const withEwb = data.taxpayers.filter((t) => t.ewb);
  const t = useMemo(() => {
    const s = (f) => withEwb.reduce((a, x) => a + f(x.ewb), 0);
    const needing = s((e) => e.outward.needing), covered = s((e) => e.outward.covered);
    return {
      bills: s((e) => e.outward.bills), value: s((e) => e.outward.value), inBills: s((e) => e.inward.bills), needing, covered,
      unmatched: s((e) => e.outward.unmatched.count), unmatchedValue: s((e) => e.outward.unmatched.value), unmatchedTax: s((e) => e.outward.unmatched.tax), g05: withEwb.filter((x) => x.ewb.outward.unmatched.count).length,
      unsupported: s((e) => e.inward.unsupported.count), unsupportedItc: s((e) => e.inward.unsupported.itc), b03: withEwb.filter((x) => x.ewb.inward.unsupported.count).length,
    };
  }, [data]);
  const rows = withEwb.map((x) => ({ x, e: x.ewb, exposure: x.ewb.outward.unmatched.tax + x.ewb.inward.unsupported.itc + x.ewb.shipTo.wrongHead.tax }))
    .filter((r) => r.exposure > 0 || r.e.vehicles.clashes > 0).sort((a, b) => b.exposure - a.exposure || b.e.vehicles.clashes - a.e.vehicles.clashes);
  const lastSynced = status?.lastFetch || withEwb.map((x) => x.ewb.fetchedAt).filter(Boolean).sort().pop();

  const upload = async (file) => {
    if (!file || !upGstin) return;
    setUploading(true);
    try {
      const r = await fetch(api(`/__ewb/upload?gstin=${encodeURIComponent(upGstin)}&name=${encodeURIComponent(file.name)}`), { method: 'POST', body: file, headers: { 'content-type': 'application/octet-stream' } });
      const body = await r.json().catch(() => ({}));
      if (!r.ok || !body.ok) toast(body.error || `Upload failed (HTTP ${r.status})`);
      else { toast(`${int(body.bills)} e-way bills stored for ${upGstin} (FY ${body.years.join(', ')})`); await reload(); }
    } catch (e) { toast(`Upload failed: ${e.message}`); }
    setUploading(false);
  };
  const busy = sync.running || uploading;

  return (
    <div className="page">
      <PageHead title="E-way bills" path={`${withEwb.length} of ${data.taxpayers.length} taxpayers · ${int(t.bills)} bills generated · ${int(t.inBills)} received`} />

      <Card title="E-way bill data" sub="Bills generated by each taxpayer and by its suppliers, matched to GSTR-1 and GSTR-2B.">
        <div className="grid g-3" style={{ alignItems: 'start' }}>
          <div>
            <div className="eyebrow">On record</div>
            <p style={{ margin: '6px 0' }}><b>{status ? `${int(status.files)} GSTIN-years` : '-'}</b>{status?.uploaded ? ` · ${status.uploaded} from uploaded exports` : ''}</p>
            <p className="muted" style={{ margin: 0, fontSize: 13 }}>{int(t.bills + t.inBills)} bills across {withEwb.length} taxpayers</p>
          </div>
          <div>
            <div className="eyebrow">Last synced</div>
            <p style={{ margin: '6px 0' }}><b>{lastSynced ? new Date(lastSynced).toLocaleString('en-IN') : '-'}</b></p>
            <p className="muted" style={{ margin: 0, fontSize: 13 }}>A sync fetches every GSTIN's bills again and re-runs the checks.</p>
          </div>
          <div>
            <div className="eyebrow">Matched</div>
            <p style={{ margin: '6px 0' }}><b>{pct(t.needing ? t.covered / t.needing : null)}</b> of sales invoices above the limit</p>
            <p className="muted" style={{ margin: 0, fontSize: 13 }}>{int(t.covered)} of {int(t.needing)} carry an e-way bill</p>
          </div>
        </div>
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center', marginTop: 14 }}>
          <button className="btn primary" onClick={() => sync.start()} disabled={busy} title="Fetch every GSTIN's e-way bills again and re-run the checks">
            <Icon name="truck" size={16} />{sync.running ? 'Syncing…' : 'Sync e-way bills'}
          </button>
          <SyncProgress job={sync.job} lastSynced={lastSynced} />
        </div>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center', marginTop: 12, paddingTop: 12, borderTop: '1px solid var(--line-2)' }}>
          <span className="muted" style={{ fontSize: 13 }}>Upload the portal's e-way bill export for</span>
          <select value={upGstin} onChange={(e) => setUpGstin(e.target.value)} aria-label="GSTIN for the upload">
            <option value="">choose a GSTIN…</option>
            {data.taxpayers.slice().sort((a, b) => a.name.localeCompare(b.name)).map((x) => <option key={x.gstin} value={x.gstin}>{x.name} · {x.gstin}</option>)}
          </select>
          <label className="btn" style={{ pointerEvents: !upGstin || busy ? 'none' : 'auto', opacity: !upGstin || busy ? 0.5 : 1 }}>
            <Icon name="upload" size={16} />{uploading ? 'Uploading…' : 'Upload .xlsx'}
            <input type="file" accept=".xlsx" hidden onChange={(e) => { upload(e.target.files?.[0]); e.target.value = ''; }} />
          </label>
        </div>
      </Card>

      <div className="grid g-4" style={{ marginTop: 12 }}>
        <Kpi label="Bills generated" value={int(t.bills)} sub={`${inr(t.value)} of goods moved`} />
        <Kpi label="Invoices covered" value={pct(t.needing ? t.covered / t.needing : null)} sub={`${int(t.covered)} of ${int(t.needing)} invoices above the limit`} fill={t.needing ? t.covered / t.needing : 0} />
        <Kpi label="Goods moved, no invoice (G-05)" value={inr(t.unmatchedValue)} sub={`${int(t.unmatched)} bills · ${t.g05} taxpayers · tax ${inr(t.unmatchedTax)}`} dot={t.unmatched ? '#b02222' : undefined} />
        <Kpi label="ITC with no movement (B-03)" value={inr(t.unsupportedItc)} sub={`${int(t.unsupported)} purchase invoices · ${t.b03} taxpayers`} dot={t.unsupported ? '#b02222' : undefined} />
      </div>

      <Card title="Taxpayers the e-way bills raise questions about" sub={`${rows.length} of ${withEwb.length} taxpayers. Ordered by tax at stake. Click a row for its bills.`} style={{ marginTop: 12 }}>
        {rows.length ? (
          <div className="tbl-wrap" style={{ maxHeight: 520 }}>
            <table className="tbl">
              <thead><tr><th>Taxpayer</th><th>Risk</th><th className="num">Bills</th><th className="num">Bills with no invoice</th><th className="num">ITC with no movement</th><th className="num">Wrong tax head (ship-to)</th><th className="num">Impossible journeys</th><th className="num">Tax at stake</th></tr></thead>
              <tbody>
                {rows.map(({ x, e, exposure }) => (
                  <tr key={x.gstin} className="clickable" onClick={() => openTaxpayer(x.gstin)} style={{ cursor: 'pointer' }} title="Open this taxpayer's e-way bills">
                    <td><b>{x.name}</b><div className="mono muted" style={{ fontSize: 11.5 }}>{x.gstin}</div></td>
                    <td><Band band={x.band} score={x.score} /></td>
                    <td className="num">{int(e.outward.bills)}</td>
                    <td className="num">{e.outward.unmatched.count ? <>{int(e.outward.unmatched.count)} · {inr(e.outward.unmatched.value)}</> : '-'}</td>
                    <td className="num">{e.inward.unsupported.count ? <>{int(e.inward.unsupported.count)} · {inr(e.inward.unsupported.itc)}</> : '-'}</td>
                    <td className="num">{e.shipTo.wrongHead.count ? `${e.shipTo.wrongHead.count} of ${e.shipTo.moves}` : '-'}</td>
                    <td className="num">{e.vehicles.clashes || '-'}</td>
                    <td className="num"><b>{inr(exposure)}</b></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : <div className="empty">The e-way bills agree with the returns for every taxpayer.</div>}
      </Card>

      <Card title="How the checks read the bills" style={{ marginTop: 12 }}>
        <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.7, color: 'var(--ink-2)' }}>
          <li><b>When a bill is needed (rule 138):</b> goods worth more than ₹50,000 moving between states; within Maharashtra, Tamil Nadu, Delhi and West Bengal the limit is ₹1 lakh. Services never move on one, and gold, jewellery and precious stones (Chapter 71) are exempt.</li>
          <li><b>G-05, goods moved with no invoice:</b> a bill the taxpayer generated whose document is not in its GSTR-1. The goods left, the sale was not reported.</li>
          <li><b>B-03, ITC with no movement:</b> a goods purchase above the limit with no bill from the supplier. Credit needs the goods to have been received (s.16(2)(b)).</li>
          <li><b>D-05, bill-to-ship-to:</b> goods delivered to one state but billed to a party in another. The place of supply is the bill-to party's state (IGST Act s.10(1)(b)), so the tax head follows it.</li>
          <li><b>Impossible journeys:</b> one vehicle starting two journeys hundreds of kilometres apart within a few hours. A lead: at least one of the bills records a movement that did not happen.</li>
        </ul>
      </Card>

      {!withEwb.length && <Card style={{ marginTop: 12 }}><div className="empty">No e-way bill data is loaded. Use <b>Sync e-way bills</b> above.</div></Card>}
    </div>
  );
}
